# Generated by Django 5.0.6 on 2024-06-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assing_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField()),
                ('assign_email', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='task_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_create_by', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.TextField()),
                ('task_id', models.TextField()),
                ('task_status', models.TextField()),
            ],
        ),
    ]
